#!/usr/bin/env python3
"""
Generate manifest.lua for net_loader.lua.

    python make_manifest.py                 # whole plugin -> manifest.lua
    python make_manifest.py movement        # only movement/ + movement.lua
    python make_manifest.py --out dist/manifest.lua

The hash is Adler-32, which is exactly what net_loader.lua computes in Lua.
"""

import argparse
import os
import sys
import zlib

SKIP_DIRS = {".git", ".bak_pre_movement2", "__pycache__", ".vscode", ".idea", "dist", "bootstrap"}
SKIP_SUFFIX = (".bak", ".pre_rewrite.bak", ".monolith.bak", ".orig", ".rej")
SKIP_FILES = {"manifest.lua", "net_loader.lua", "json.lua", "http_runtime.lua"}


def version_of(root):
    path = os.path.join(root, "version.lua")
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                if "version" in line and "=" in line and '"' in line:
                    return line.split('"')[1]
    except OSError:
        pass
    return "unknown"


def collect(root, subset):
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for fn in sorted(filenames):
            if not fn.endswith(".lua") or fn.endswith(SKIP_SUFFIX):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.sep, "/")
            if rel in SKIP_FILES:
                continue
            if subset and not (rel == subset + ".lua" or rel.startswith(subset + "/")):
                continue
            out.append(rel)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("subset", nargs="?", help='limit to one tree, e.g. "movement"')
    ap.add_argument("--root", default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    root = args.root
    files = collect(root, args.subset)
    if not files:
        sys.exit("no .lua files matched")

    rows, total = [], 0
    for rel in files:
        data = open(os.path.join(root, rel), "rb").read()
        data = data.replace(b"\r\n", b"\n")
        h = zlib.adler32(data) & 0xFFFFFFFF
        rows.append((rel, f"{h:08x}", len(data)))
        total += len(data)

    out_path = args.out or os.path.join(root, "manifest.lua")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)

    width = max(len(r[0]) for r in rows) + 3
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("-- Generated by make_manifest.py - do not edit by hand.\n")
        fh.write("-- Consumed by net_loader.lua; hash is Adler-32 of the LF-normalised bytes.\n")
        fh.write("return {\n")
        fh.write(f'    version = "{version_of(root)}",\n')
        fh.write(f"    count   = {len(rows)},\n")
        fh.write(f"    bytes   = {total},\n")
        fh.write("    files = {\n")
        for rel, h, size in rows:
            path = f'"{rel}",'
            fh.write(f'        {{ path = {path:<{width}} hash = "{h}", size = {size} }},\n')
        fh.write("    },\n")
        fh.write("}\n")

    print(f"{out_path}: {len(rows)} files, {total:,} bytes")


if __name__ == "__main__":
    main()
